---
- name: Include default variables
  ansible.builtin.include_vars:
    file: ../../../vars/main.yml

- name: Copy the config file to required location
  ansible.builtin.template:
    src: nginx.config.j2
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Test Nginx
  ansible.builtin.command: nginx -t
  changed_when: false
  become: true

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: Use Certbot to generate certificates
  ansible.builtin.shell: |
     certbot --nginx -d {{ sub_domain }} --non-interactive --agree-tos -m {{ email }}
  changed_when: false
  become: true

- name: Print Jenkins Password
  ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  become: true

- name: Jenkins setup wizard disable
  ansible.builtin.lineinfile:
    path: /etc/default/jenkins
    line: JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
  become: true

- name: Make a directory called groovy init
  ansible.builtin.file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    mode: 0777
  become: true

- name: File basic-security.groovy should be copied to the directory init.groovy.d
  ansible.builtin.template:
    src:  basic-security.groovy
    dest: "/var/lib/jenkins/init.groovy.d"
    owner: root
    group: root
    mode: '0777'
  become: true
  changed_when: false

- name: Copy plugins.sh template to ubuntu directory
  ansible.builtin.template:
    src: plugins.sh
    dest: "/home/ubuntu"
    owner: root
    group: root
    mode: '0777'
  become: true
  changed_when: false

- name: Download jenkins cli into ubuntu home directory
  ansible.builtin.get_url:
    url: http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest: /home/ubuntu
    mode: '0777'
  retries: 5
  delay: 5
  become: true
  register: result
  until: result is succeeded

- name: Run plugins scripts
  ansible.builtin.shell: "/home/ubuntu/plugins.sh {{user}} {{user_password}}"
  args:
    executable: /bin/bash
  become: true

- name: Restart jenkins service
  ansible.builtin.service:
    name: jenkins
    state: restarted
  become: true

- name: Before continuing, wait for Jenkins to launch.
  ansible.builtin.uri:
    url: "http://localhost:8080"
    method: GET
    return_content: "yes"
    timeout: 5
    body_format: raw
    follow_redirects: "no"
    status_code: 200,403
  register: result
  until: (result.status == 403 or result.status == 200) and (result.content.find("Please wait while") == -1)
  retries: 60
  delay: 5
  changed_when: false
  check_mode: false

- name: Delete groovy init file
  ansible.builtin.file:
    path: "/var/lib/jenkins/init.groovy.d/basic-security.groovy"
    state: absent
  become: true
