---
- name: Include default variables
  ansible.builtin.include_vars:
    file: ../../../vars/main.yml

- name: Copy the config file to required location
  ansible.builtin.template:
    src: nginx.config.j2
    dest: "/etc/nginx/sites-available/default"
    owner: root
    group: root
    mode: 0644
  become: true

- name: Test Nginx
  ansible.builtin.command: nginx -t
  changed_when: false
  become: true

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true

- name: Use Certbot to generate certificates
  ansible.builtin.shell: |
     certbot --nginx -d {{ sub_domain }} --non-interactive --agree-tos -m {{ email }}
  changed_when: false
  become: true
